export const NAV_ITEMS = [
  { key: "dashboard",      label: "Dashboard",          icon: "Home",       path: "/admin",                  roles: ["superadmin","admin","hod","cc","faculty","student"] },
  { key: "management",     label: "Management",         icon: "Building",   path: "/admin/management",       roles: ["superadmin"] },
  { key: "settings",       label: "Institution Settings",icon: "Settings",   path: "/settings",               roles: ["superadmin"] },
  { key: "hods",           label: "HODs",                icon: "UserTie",    path: "/hods",                   roles: ["admin"] },
  { key: "reports",        label: "Reports",             icon: "BarChart",   path: "/reports",                roles: ["admin","hod"] },
  { key: "fee-policy",     label: "Fee Policy",          icon: "Wallet",     path: "/fee-policy",             roles: ["admin"] },
  { key: "inst-notices",   label: "Institution Notices", icon: "Megaphone",  path: "/notices",                roles: ["admin"] },
  { key: "management",     label: "Staff Management",    icon: "Users",      path: "/hod/management",         roles: ["hod"] },
  { key: "academic",       label: "Academic Structure",  icon: "Layers",     path: "/hod/academic-structure", roles: ["hod"] },
  { key: "assignments",    label: "Teaching Assignments",icon: "Link",       path: "/assignments",            roles: ["hod"] },
  { key: "roster",         label: "Student Roster",      icon: "List",       path: "/cc/roster",                 roles: ["cc"] },
  { key: "disputes",       label: "Attendance Disputes", icon: "Flag",       path: "/cc/workspace?tab=disputes", roles: ["cc"] },
  { key: "my-classes",     label: "My Classes",          icon: "Calendar",   path: "/my-classes",             roles: ["faculty"] },
  { key: "notes",          label: "Notes",               icon: "FileText",   path: "/faculty/notes",          roles: ["faculty"] },
  { key: "marks-entry",    label: "Marks Entry",         icon: "Edit",       path: "/marks-entry",            roles: ["faculty"] },
  { key: "analytics",      label: "Subject Analytics",   icon: "BarChart2",  path: "/faculty/analytics",      roles: ["faculty"] },
  { key: "attendance",     label: "Attendance",          icon: "CheckSquare",path: "/attendance",             roles: ["student"] },
  { key: "results",        label: "Results",             icon: "Award",      path: "/results",                roles: ["student"] },
  { key: "fees",           label: "Fees",                icon: "CreditCard", path: "/fees",                   roles: ["student"] },
  { key: "cc-notices",     label: "Notices",             icon: "Bell",       path: "/cc/workspace?tab=notices",roles: ["cc"] },
  { key: "notices",        label: "Notices",             icon: "Bell",       path: "/notices",                roles: ["faculty","student"] },
  { key: "profile",        label: "Profile",             icon: "User",       path: "/profile",                roles: ["superadmin","admin","hod","cc","faculty","student"] },
];
